import type { RocketParams } from '../types/rocket';

export const defaultParams: RocketParams = {
  initialMass: 12,
  fuelMass: 5,
  thrust: 900,
  isp: 180,
  launchAngleDeg: 82,
  dragCoefficient: 0.38,
  referenceArea: 0.012,
  launchRailLength: 2,
  windSpeed: 0,
  thrustRampPercent: 18,
};

export const presets = {
  starter: {
    label: '기본형',
    params: defaultParams,
  },
  sounding: {
    label: '고고도 관측 로켓',
    params: {
      initialMass: 28,
      fuelMass: 11,
      thrust: 2400,
      isp: 215,
      launchAngleDeg: 86,
      dragCoefficient: 0.26,
      referenceArea: 0.009,
      launchRailLength: 4,
      windSpeed: 6,
      thrustRampPercent: 12,
    },
  },
  windy: {
    label: '강풍 테스트',
    params: {
      initialMass: 16,
      fuelMass: 6.5,
      thrust: 1250,
      isp: 175,
      launchAngleDeg: 78,
      dragCoefficient: 0.42,
      referenceArea: 0.015,
      launchRailLength: 3,
      windSpeed: 18,
      thrustRampPercent: 24,
    },
  },
  sprint: {
    label: '고추력 스프린트',
    params: {
      initialMass: 9,
      fuelMass: 3,
      thrust: 1800,
      isp: 165,
      launchAngleDeg: 80,
      dragCoefficient: 0.34,
      referenceArea: 0.008,
      launchRailLength: 2.4,
      windSpeed: 2,
      thrustRampPercent: 8,
    },
  },
  endurance: {
    label: '장연소 비행',
    params: {
      initialMass: 24,
      fuelMass: 10,
      thrust: 1350,
      isp: 255,
      launchAngleDeg: 84,
      dragCoefficient: 0.23,
      referenceArea: 0.01,
      launchRailLength: 4.2,
      windSpeed: 4,
      thrustRampPercent: 10,
    },
  },
  heavyLift: {
    label: '중량 탑재형',
    params: {
      initialMass: 42,
      fuelMass: 14,
      thrust: 3200,
      isp: 210,
      launchAngleDeg: 88,
      dragCoefficient: 0.31,
      referenceArea: 0.018,
      launchRailLength: 5.5,
      windSpeed: 5,
      thrustRampPercent: 14,
    },
  },
  longRange: {
    label: '장거리 사선 발사',
    params: {
      initialMass: 18,
      fuelMass: 7.2,
      thrust: 1500,
      isp: 205,
      launchAngleDeg: 64,
      dragCoefficient: 0.29,
      referenceArea: 0.01,
      launchRailLength: 3.5,
      windSpeed: 3,
      thrustRampPercent: 16,
    },
  },
  thinAir: {
    label: '저항 최소화 실험',
    params: {
      initialMass: 14,
      fuelMass: 5.8,
      thrust: 1280,
      isp: 230,
      launchAngleDeg: 87,
      dragCoefficient: 0.14,
      referenceArea: 0.005,
      launchRailLength: 3.8,
      windSpeed: 1,
      thrustRampPercent: 11,
    },
  },
} satisfies Record<string, { label: string; params: RocketParams }>;

export type PresetKey = keyof typeof presets;
